# Generated by Django 4.0.4 on 2022-04-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('todo', models.CharField(default='', max_length=50)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
